### ISSUE TITLE
Which SDK to use?

### ISSUE THREAD

**Issue by mpapec** [HandCash/handcash-connect-sdk-docs#2]
Example at
https://handcash.github.io/handcash-connect-sdk-js-beta-docs/#/user-authorization?id=your-app-authorization

```
const { AppPermissions } = require('@handcash/handcash-connect-beta');

const redirectionLoginUrl = AppAuthorization.getRedirectionLoginUrl('public unique identifier of your app');

// Use redirectionLoginUrl to redirect users in your front-end (browser, native app, ...).
```

gives syntax error. 

Am I looking at correct docs for SDK?

**Comment by rafa-js** [comment]
> Example at
> https://handcash.github.io/handcash-connect-sdk-js-beta-docs/#/user-authorization?id=your-app-authorization
> 
> ```
> const { AppPermissions } = require('@handcash/handcash-connect-beta');
> 
> const redirectionLoginUrl = AppAuthorization.getRedirectionLoginUrl('public unique identifier of your app');
> 
> // Use redirectionLoginUrl to redirect users in your front-end (browser, native app, ...).
> ```
> 
> gives syntax error.
> 
> Am I looking at correct docs for SDK?

Hi @mpapec, thanks for opening the issue.

We have detected some inconsistencies in the docs like the one you are pointing. 

This issue has been fixed. Check the section again and let me know!

**Comment by mpapec** [comment]
Thanks for swift reply, but there is still an issue with require()

```
/home/mpapec/w/hand.js:2
const { AppAuthorization } = require('@handcash/handcash-connect-beta');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Node is v4.2.6

**Comment by mpapec** [comment]
Thanks for swift response; I've got `https://handcash-web-beta.firebaseapp.com/#/authorizeApp?appId=<myUniqId>`
which required phone and email verification.

Does it make sense to post further details over public issue thread?
